spring:
  application:
    name: guestbook
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://15.164.103.52:3306/guestbook
    username: guestbook
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - src/main/webapp
      additional-exclude: static/**,templates/**
    livereload:
      enabled: true
  thymeleaf:
    cache: false