server:
  port: 9999
spring:
  application:
    name: member_post
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://15.164.103.52:3306/post
    username: test
    password: 123
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml  
  type-aliases-package: com.example.member_post.vo
  configuration:
    map-underscore-to-camel-case: true
