server:
  port: 9999
spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - src/main/webapp
      additional-exclued: static/**,templates/**
    livereload:
      enabled: true
    
  application:
    name: member_post
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://15.164.103.52:3306/post
    # driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://15.164.103.52:3306/post
    username: test
    password: 123
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml  
  type-aliases-package: com.example.member_post.vo
  configuration:
    map-underscore-to-camel-case: true
